# bootstrap.yml 공통 환경설정 파일. 기본 프로파일은 native로 지정

#sql: SELECT APP_NAME,TYPE,NAME,VALUE FROM app_config app, app_config_param param
#  WHERE app.APP_CONFIG_UID=param.APP_CONFIG_UID
# AND APP_NAME=? AND TYPE=?
#order: 0

server:
  port: 9001
spring:
  application:
    name: configuration-server
  profiles:
    active: native, local, jdbc
  datasource:
    url: jdbc:mariadb://localhost:33306/zenca?autoReconnect=true
    driver-class-name: org.mariadb.jdbc.Driver
    platform: mysql
    username: root
    password: mocomsys1$
  cloud:
    config:
      server:
        default-label: latest
        jdbc:
          sql: SELECT NAME, VALUE FROM config C, config_properties P WHERE C.APP_CONFIG_UID=P.APP_CONFIG_UID AND C.APPLICATION=? and C.PROFILE=? and C.LABEL=?
eureka:
  client:
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG