# application-dev.yml
logging:
  level:
    root: info
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:33306/MIGW_META
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mocomsys1$
    jpa:
      open-in-view: false
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        show_sql: true
        format_sql: true